apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
        - name: spark-worker
          image: apache/spark:3.5.3
          env:
            - name: SPARK_MODE
              value: "worker"
            - name: SPARK_MASTER_URL
              value: "spark://spark-master-service:7077"
            - name: SPARK_WORKER_MEMORY
              value: "2G"
            - name: SPARK_WORKER_CORES
              value: "2"
          ports:
            - containerPort: 8081