apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master
  labels:
    app: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-master
  template:
    metadata:
      labels:
        app: spark-master
    spec:
      containers:
        - name: spark-master
          image: apache/spark:3.5.3
          env:
            - name: SPARK_MODE
              value: "master"
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
          ports:
            - containerPort: 7077
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-master
  ports:
    - name: cluster-rpc
      port: 7077
      targetPort: 7077
    - name: web-ui
      port: 8080
      targetPort: 8080